app/blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import ArticleListView, ArticleDetailView

app_name = BlogConfig.name

urlpatterns = [
    path('list/', ArticleListView.as_view(), name='list'),
    path('read/<int:pk>/', ArticleDetailView.as_view(), name='read'),
]

app/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
# в алфавитном порядке
urlpatterns = [
    path('', include('users.urls', namespace='users')),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('service/', include('service.urls', namespace='service')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/service/urls.py
from django.urls import path

from service.apps import ServiceConfig
from service.views import *

app_name = ServiceConfig.name

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('customer/', CustomerListView.as_view(), name='service'),
    path('create_customer/', CustomerCreateView.as_view(), name='create_customers'),
    path('mail/', MailingListView.as_view(), name='mail'),
    path('message/', MessageListView.as_view(), name='message'),
    path('create_message/', MessageCreateView.as_view(), name='create_message'),
    path('create_mail/', MailingCreateView.as_view(), name='create_mail'),
    path('update_customer/<int:pk>', CustomerUpdateView.as_view(), name='update_customer'),
    path('update_message/<int:pk>', MessageUpdateView.as_view(), name='update_message'),
    path('update_mail/<int:pk>', MailingUpdateView.as_view(), name='update_mail'),
    path('delete_customer/<int:pk>', CustomerDeleteView.as_view(), name='delete_customer'),
    path('delete_message/<int:pk>', MessageDeleteView.as_view(), name='delete_message'),
    path('delete_mail/<int:pk>', MailingDeleteView.as_view(), name='delete_mail'),
    path('detail_customer/<int:pk>', CustomerDetailView.as_view(), name='detail_customer'),
    path('detail_mail/<int:pk>', MailingDetailView.as_view(), name='detail_mail'),
    path('detail_massage/<int:pk>', MessageDetailView.as_view(), name='detail_message'),
    path('mail_customer/', mail_customer_confirm, name='status'),
    path('statistic/', statistic, name='statistic'),
    path('deactivate_mail/<int:pk>', turn_off_mailing, name='deactivate'),

]

app/service/models.py
from django.db import models
from django.conf import settings
from django.utils.datetime_safe import date

NULLABLE = {'blank': True, 'null': True}


class Customers(models.Model):
    user_create = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='пользователь',
                                    **NULLABLE)
    email = models.CharField(max_length=150, verbose_name='контактный email')
    name = models.CharField(max_length=250, verbose_name='фио')
    comment = models.TextField(verbose_name='комментарий', **NULLABLE)

    def __str__(self):
        return self.name

    class Meta:
        permissions = [
            ('turn_off',
             'Can turn off mailing')
        ]


class Mailing(models.Model):
    objects = None
    PERIOD_ONE_DAY = 'once_day'
    PERIOD_ONE_WEEK = 'once_week'
    PERIOD_ONE_MONTH = 'once_month'
    PERIODS = (
        ('once_day', 'раз в день'),
        ('once_week', 'раз в неделю'),
        ('once_month', 'раз в месяц'),
    )
    STATUSE_COMPLETED = 'completed,'
    STATUSE_CREATED = 'created'
    STATUSE_LAUNCHED = 'launched'
    STATUSE_DEACTIVATION = 'deactivated'
    STATUSES = (
        ('completed', 'завершена'),
        ('created', 'создана'),
        ('launched', 'запущена'),
        ('deactivated', 'деактивирован'),
    )
    user_create = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='пользователь', on_delete=models.CASCADE,
                                    **NULLABLE)
    add_customer = models.ForeignKey('service.Customers', verbose_name='Клиент', on_delete=models.SET_NULL, null=True)
    add_message = models.ForeignKey('service.Message', verbose_name='Сообщение', on_delete=models.SET_NULL, null=True)
    time_mailing = models.TimeField(verbose_name='время рассылки', **NULLABLE)
    change_time = models.CharField(choices=PERIODS, default=PERIOD_ONE_WEEK, max_length=15,
                                   verbose_name='периодичность')
    state_mail = models.CharField(choices=STATUSES, default=STATUSE_COMPLETED, max_length=15,
                                  verbose_name='статус рассылки')
    first_date = models.DateField(default=date.today, verbose_name='начальная_дата', )
    last_date = models.DateField(default=date.today, verbose_name='конечная_дата', )


class Message(models.Model):
    user_create = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='пользователь', on_delete=models.CASCADE,
                                    **NULLABLE)
    topic_message = models.CharField(max_length=250, verbose_name='тема письма', **NULLABLE)
    letter = models.TextField(verbose_name='тело письма')

    def __str__(self):
        return self.topic_message


class TryMail(models.Model):
    date = models.DateTimeField(auto_now_add=True, verbose_name='дата и время последней попытки')
    status = models.CharField(max_length=15, verbose_name='статус попытки')
    answer = models.CharField(max_length=150, verbose_name='ответ почтового сервера', **NULLABLE)

app/service/forms.py
from django import forms

from base.forms import StyleFormMixin
from service.models import Customers, Mailing, Message


class CustomerForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Customers
        exclude = ['user_create', ]


class MailingForm(StyleFormMixin, forms.ModelForm):
    STATUSES = (
        ('completed', 'завершена'),
        ('created', 'создана'),
        ('launched', 'запущена'),
    )
    state_mail = forms.ChoiceField(choices=STATUSES, )

    class Meta:
        model = Mailing
        exclude = ['user_create', ]


class MessageForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Message
        exclude = ['user_create', ]

app/service/views/view1.py
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, CreateView

from base.service import count_mail_all, count_active_mail, count_customer_all
from blog.models import Blog
from service.forms import CustomerForm, MailingForm, MessageForm
from service.models import Mailing, Customers, Message


class HomePageView(TemplateView):
    template_name = 'service/home.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['blog'] = Blog.objects.all().order_by('?')[:3]
        context_data['count_all_mail'] = count_mail_all()
        context_data['count_active_mail'] = count_active_mail()
        context_data['customer'] = count_customer_all()
        return context_data


class MailingListView(ListView):
    model = Mailing

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.request.user.has_perm('service.view_mailing'):
            return queryset

        return queryset.filter(user_create=self.request.user)


class CustomerCreateView(CreateView):
    model = Customers
    form_class = CustomerForm
    success_url = reverse_lazy('service:service')

    def form_valid(self, form):
        if form.is_valid():
            self.object = form.save(commit=False)
            self.object.user_create = self.request.user
            self.object.save()
        return super().form_valid(form)


class MailingCreateView(CreateView):
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('service:mail')

    def form_valid(self, form):
        if form.is_valid():
            self.object = form.save(commit=False)
            self.object.user_create = self.request.user
            self.object.save()
        return super().form_valid(form)


class MessageCreateView(CreateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('service:message')

    def form_valid(self, form):
        if form.is_valid():
            self.object = form.save(commit=False)
            self.object.user_create = self.request.user
            self.object.save()
        return super().form_valid(form)

app/service/views/view2.py
from django.contrib.auth.decorators import permission_required
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse

from service.models import TryMail, Mailing
from service.sendmail import mail_customer


def statistic(request):
    context = {
        'object_list': TryMail.objects.all()
    }
    return render(request, 'service/statistic.html', context)


def mail_customer_confirm(request):
    id = request.user.id
    mail_customer(id)
    return redirect(reverse('service:mail'))


@permission_required('service.turn_off')
def turn_off_mailing(request, pk):
    current_mailing = get_object_or_404(Mailing, pk=pk)
    if current_mailing:
        current_mailing.state_mail = Mailing.STATUSE_DEACTIVATION
        current_mailing.save()
    return redirect(request.META.get('HTTP_REFERER'))

app/service/views/view3.py
from msilib.schema import ListView

from django.urls import reverse_lazy
from django.views.generic import UpdateView, DeleteView, DetailView

from service.forms import CustomerForm, MessageForm, MailingForm
from service.models import Customers, Message, Mailing


class UserFilterMixin:
    def get_queryset(self):
        return self.model.objects.filter(user_create=self.request.user)


class CustomerListView(ListView, UserFilterMixin):
    model = Customers


class MessageListView(ListView, UserFilterMixin):
    model = Message


class CustomerUpdateView(UpdateView, UserFilterMixin):
    model = Customers
    form_class = CustomerForm
    success_url = reverse_lazy('service:service')


class MessageUpdateView(UpdateView, UserFilterMixin):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('service:message')


class MailingUpdateView(UpdateView, UserFilterMixin):
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('service:mail')


class CustomerDeleteView(DeleteView, UserFilterMixin):
    model = Customers
    success_url = reverse_lazy('service:service')


class MessageDeleteView(DeleteView, UserFilterMixin):
    model = Message
    success_url = reverse_lazy('service:message')


class MailingDeleteView(DeleteView, UserFilterMixin):
    model = Mailing
    success_url = reverse_lazy('service:mail')


class CustomerDetailView(DetailView, UserFilterMixin):
    model = Customers


class MailingDetailView(DetailView, UserFilterMixin):
    model = Mailing


class MessageDetailView(DetailView, UserFilterMixin):
    model = Message

app/service/templates/service/includes/footer.html
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
        <div class="col-12 col-md">
            ServiceSendMail
            <small class="d-block mb-3 text-muted">&copy; 2023</small>
        </div>
        <div class="col-6 col-md">
            <h5>Категории</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="{% url 'service:service' %}">Клиенты</a></li>
                <li><a class="text-muted" href="{% url 'service:mail' %}">Настройки рассылок</a></li>
                <li><a class="text-muted" href="{% url 'service:message' %}">Сообщения</a></li>
                <li><a class="text-muted" href="{% url 'service:statistic' %}">Статистика</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>Дополнительно</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Мы пишем</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>О нас</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Контакты</a></li>
            </ul>
        </div>
    </div>
</footer>

app/service/templates/service/includes/main-menu.html
<div class="b-example-divider"></div>
<header class="p-3 text-bg-light">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap">
                    <use xlink:href="#bootstrap"></use>
                </svg>
            </a>
            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <a href="{% url 'service:service' %}" class="nav-link px-2 link-secondary">Клиенты</a>
                <li><a href="{% url 'service:mail' %}" class="nav-link px-2 link-secondary">Рассылки</a></li>
                <li><a href="{% url 'service:message' %}" class="nav-link px-2 link-secondary">Сообщения</a></li>
                <li><a href="{% url 'service:statistic' %}" class="nav-link px-2 link-secondary">Статистика</a></li>
            </ul>
        </div>
    </div>
</header>

app/service/templates/service/includes/main_menu.html
<div class="b-example-divider"></div>
<header class="p-3 text-bg-light">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap">
                    <use xlink:href="#bootstrap"></use>
                </svg>
            </a>
            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <a href="{% url 'service:service' %}" class="nav-link px-2 link-secondary">Клиенты</a>
                <li><a href="{% url 'service:mail' %}" class="nav-link px-2 link-secondary">Рассылки</a></li>
                <li><a href="{% url 'service:message' %}" class="nav-link px-2 link-secondary">Сообщения</a></li>
                <li><a href="{% url 'service:statistic' %}" class="nav-link px-2 link-secondary">Статистика</a></li>
            </ul>
        </div>
    </div>
</header>