app/blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import ArticleListView, ArticleDetailView

app_name = BlogConfig.name

urlpatterns = [
    path('list/', ArticleListView.as_view(), name='list'),
    path('read/<int:pk>/', ArticleDetailView.as_view(), name='read'),
]

app/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
# в алфавитном порядке
urlpatterns = [
    path('', include('users.urls', namespace='users')),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('service/', include('service.urls', namespace='service')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from users.apps import UsersConfig
from users.views import *


app_name = UsersConfig.name

urlpatterns = [
    path('', SigninView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', SignupView.as_view(), name='register'),
    path('register/success/', SignupSuccessView.as_view(), name='register_success'),
    path('password/reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('password/reset/<uidb64>/confirm/<token>/', CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password/reset/done/',
         CustomPasswordResetDoneView.as_view(template_name='users/reset_confirm.html'), name='password_reset_done'),
    path('password/reset/complete/', CustomPasswordResetCompleteView.as_view(template_name='users/password_reset_form.html'),
         name='password_reset_complete'),
    path('verify/<str:token>/', verify_email, name='verify_email'),
    path('simple/reset/', simple_reset_password, name='simple_reset'),
    path('user_list/', UsersListView.as_view(), name='user_list'),
    path('user_change/<int:pk>/', user_status_change, name='user_change')
]

app/base/models.py
from django.db import models

# Create your models here.

app/users/models.py
from django.contrib.auth.models import AbstractUser, UserManager
from django.db import models
from django.contrib.auth.hashers import make_password
from django.conf import settings

NULLABLE = {'blank': True, 'null': True}


class CustomUserManager(UserManager):
    def create_superuser(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True')
        return self._create_user(email, password, **extra_fields)

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.password = make_password(password)
        user.save(using=self._db)
        return user


class Meta:
    permissions = [
        (
            'change_status',
            'Can change is_staff'
        )
    ]
    unique_together = (
        ('email', 'phone'),
    )


class User(AbstractUser):
    objects = CustomUserManager()  # менеджер моделей

    username = None
    # user_create_id = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='пользователь', on_delete=models.CASCADE,
    #                                    **NULLABLE)
    email = models.EmailField(verbose_name='почта', unique=True)
    phone = models.CharField(max_length=50, verbose_name='номер телефона')
    avatar = models.ImageField(upload_to='users/', verbose_name='аватар')
    country = models.CharField(max_length=100, verbose_name='страна')
    email_confirmed = models.BooleanField(default=False)
    token = models.CharField(max_length=20, verbose_name='токен', **NULLABLE)
    token_expired = models.DateTimeField(**NULLABLE)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

app/base/forms.py
from django import forms


class StyleFormMixin:

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            if isinstance(field.widget, forms.widgets.CheckboxInput):
                field.widget.attrs['class'] = 'form-check-input'
            elif isinstance(field.widget, forms.DateTimeInput):
                field.widget.attrs['class'] = 'form-control flatpickr-basic'
            elif isinstance(field.widget, forms.DateInput):
                field.widget.attrs['class'] = 'form-control datepicker'
            elif isinstance(field.widget, forms.TimeInput):
                field.widget.attrs['class'] = 'form-control flatpickr-time'
            elif isinstance(field.widget, forms.widgets.SelectMultiple):
                field.widget.attrs['class'] = 'form-control select2 select2-multiple'
            elif isinstance(field.widget, forms.widgets.Select):
                field.widget.attrs['class'] = 'form-control select2'
            else:
                field.widget.attrs['class'] = 'form-control'

            field.help_text = ''

app/users/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UsernameField, PasswordResetForm, \
    UserChangeForm
from base.forms import StyleFormMixin
from users.models import User


class CustomEditUserForm(StyleFormMixin, UserChangeForm):
    class Meta:
        model = User
        fields = ('email',)


class SigninForm(StyleFormMixin, AuthenticationForm):
    pass


class SignupForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ('email',)
        field_classes = {'username': UsernameField}


class CustomPasswordResetForm(StyleFormMixin, PasswordResetForm):
    pass

app/base/views.py
from django.shortcuts import render

# Create your views here.

app/users/views/view1.py
from msilib.schema import ListView

from django.contrib.auth.decorators import permission_required
from django.contrib.auth.views import LoginView
from django.http import HttpResponseForbidden
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, TemplateView, UpdateView

from users.forms import SignupForm, SigninForm, CustomEditUserForm
from users.models import User
from users.service import set_verify_token_and_send_mail


class SigninView(LoginView):
    template_name = 'users/login.html'
    form_class = SigninForm


class SignupView(CreateView):
    template_name = 'users/register.html'
    model = User
    form_class = SignupForm
    success_url = reverse_lazy('users:register_success')

    def form_valid(self, form):
        if form.is_valid():
            self.object = form.save()
            set_verify_token_and_send_mail(self.object)
            self.object.is_active = True
            self.object.save()
        return super().form_valid(form)


class SignupSuccessView(TemplateView):
    template_name = 'users/signup_success.html'


class VerifySuccessView(TemplateView):
    template_name = 'users/verify_success.html'


class UsersListView(ListView):
    model = User
    template_name = 'users/user_list.html'

@permission_required('users.change_status')
def user_status_change(request, pk):
    current_user = get_object_or_404(User, pk=pk)
    if current_user.is_superuser:
        return HttpResponseForbidden()
    if current_user.is_active:
        current_user.is_active = False
    else:
        current_user.is_active = True
    current_user.save()
    return redirect(request.META.get('HTTP_REFERER'))

class UserEditProfileView(UpdateView):
    model = User
    template_name = 'users/simple_reset.html'
    form_class = CustomEditUserForm
    success_url = reverse_lazy('users:home')

    def get_object(self, queryset=None):
        return self.request.user

app/users/views/view2.py
from datetime import datetime

import pytz
from django.conf import settings
from django.contrib.auth.decorators import permission_required
from django.http import HttpResponseForbidden
from django.shortcuts import render, redirect, get_object_or_404

from users.models import User
from users.service import generate_password_and_send_mail


def verify_email(request, token):
    current_user = User.objects.filter(token=token).first()
    if current_user:
        now = datetime.now(pytz.timezone(settings.TIME_ZONE))
        if now > current_user.token_expired:
            current_user.delete()
            return render(request, 'users/verify_token_expired.html')

        current_user.is_active = True
        current_user.token = None
        current_user.token_expired = None
        current_user.save()
        return redirect('users:login')
    return render(request, 'users/verify_failed.html')


def simple_reset_password(request):
    if request.method == 'POST':
        current_user = User.objects.filter(email=request.POST.get('email')).first()
        if current_user:
            generate_password_and_send_mail(current_user)
        return render(request, 'users/simple_reset.html')


def confirm_new_generated_password(request):
    current_user = User.objects.filter(email=request.GET.get('email')).first()
    current_user.password = current_user.new_password
    current_user.new_password = None
    current_user.save()
    return redirect(...)

app/users/views/view3.py
from django.conf import settings
from django.contrib.auth.views import PasswordResetView, PasswordResetConfirmView, PasswordResetDoneView, \
    PasswordResetCompleteView
from django.urls import reverse_lazy

from users.forms import CustomPasswordResetForm


class CustomPasswordResetView(PasswordResetView):
    template_name = 'users/password_reset_form.html'
    form_class = CustomPasswordResetForm
    success_url = reverse_lazy('users:password_reset_done')
    email_template_name = 'users/email_reset.html'
    from_email = settings.EMAIL_HOST_USER


class CustomPasswordResetConfirmView(PasswordResetConfirmView):
    template_name = 'users/reset_confirm.html'
    success_url = reverse_lazy('users:password_reset_complete')


class CustomPasswordResetDoneView(PasswordResetDoneView):
    template_name = 'users/reset_done.html'


class CustomPasswordResetCompleteView(PasswordResetCompleteView):
    template_name = 'users/reset_complete.html'

app/users/templates/users/account_activation_email.html
{% autoescape off %}
Hi {{ user.username }},

Please click on the link below to confirm your registration:

http://{{ domain }}{% url 'users:activate' token=token %}
{% endautoescape %}

app/users/templates/users/email_reset.html
Someone asked for password reset for email {{ email }}. Follow the link below:
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}

app/users/templates/users/login.html
{% extends 'users/base.html' %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <h1 class="h3 mb-3 fw-normal">Авторизуйтесь</h1>
    {{ form.as_p }}
    <button class="w-100 btn btn-lg btn-primary" type="submit">Вход</button>
    <a class="btn btn-link" href="{% url 'users:password_reset' %}">Забыли пароль?</a>
    <br>
    <a class="btn btn-link" href="{% url 'users:register'%}">Нет аккаунта?</a>
</form>
{% endblock %}

app/users/templates/users/password_reset_form.html
{% extends 'users/base.html' %}

{% block content %}
<form method="post">
    {% csrf_token %}

    <h1 class="h3 mb-3 fw-normal">Сброс пароля</h1>
    {{ form.as_p }}
    <button class="w-100 btn btn-lg btn-primary" type="submit">Сброс</button>
    <br>
    <a class="btn btn-link" href="{% url 'users:login' %}">Передумал</a>
</form>
{% endblock %}

app/users/templates/users/register.html
{% extends 'users/base.html' %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <h1 class="h3 mb-3 fw-normal">Зарегистрируйтесь</h1>
    {{ form.as_p }}
    {% csrf_token %}
    <button class="w-100 btn btn-lg btn-primary" type="submit">Регистрация</button>
    <a class="btn btn-link" href="{% url 'users:login' %}">Есть аккаунт?</a>
</form>

{% endblock %}

app/users/templates/users/reset_complete.html
{% extends 'users/base.html' %}

{% block content %}

<p>
    И снова поздравляем! Теперь можно пользоваться сервисом
</p>
<a href="{% url 'users:login' %}" class="btn btn-link">
    На главную
</a>

{% endblock %}

app/users/templates/users/reset_confirm.html
{% extends 'users/base.html' %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <h1 class="h3 mb-3 fw-normal">Введите новый пароль</h1>
    {{ form.as_p }}
    <button class="w-100 btn btn-lg btn-primary" type="submit">Изменить пароль</button>
</form>
{% endblock %}

app/users/templates/users/reset_done.html
{% extends 'users/base.html' %}

{% block content %}

<p>
    Иди на почту и проверяй ссылку
</p>
<a href="{% url 'users:login' %}" class="btn btn-link">
    На главную
</a>

{% endblock %}

app/users/templates/users/signup_success.html
{% extends 'users/base.html' %}

{% block content %}

<p>
    Поздравляем! Вы зарегались и скоро сможете продавать или покупать лодочки, если зп позволяет :)
</p>
<p>
    Пожалуйста, чтобы пользоваться сервисом, проверьте почту и перейдите по ссылке из письма от нас
</p>
<a href="{% url 'users:login' %}" class="btn btn-link">
    Потом загляну на почту
</a>

{% endblock %}

app/users/templates/users/user_form.html
{% extends 'users/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-6">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Сохранить</button>
            </form>
        </div>
    </div>
{% endblock %}

app/users/templates/users/user_list.html
{% extends 'service/base.html' %}
{% block content %}
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-primery border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Service</h5>
    <nav class="ms-5">
        <h6 class="my-0 mr-md-auto font-weight-normal">Меню менеджера</h6>
    </nav>
</div>
<div class="container">
    <table class="table">
        <thead class="table-light" style="text-align: center">
        <th scope="col">контактный email</th>
        <th scope="col">Имя</th>
        <th scope="col">Фамилия</th>
        <th scope="col">Статус</th>
        <th scope="col"></th>
        </thead>
        <tbody>
        {% for object in object_list %}
        <tr>
            <td class="table-light" style="text-align: center">{{object.email}}</td>
            <td class="table-light" style="text-align: center">{{object.first_name}}</td>
            <td class="table-light" style="text-align: center">{{object.last_name}}</td>
            <td class="table-light" style="text-align: center">{{object.is_active}}</td>
            <td class="table-light" style="text-align: center">
                {% if perms.users.change_status %}
                {% if object.is_active %}
                <a class="p-2 btn btn-info" href="{% url 'users:user_change' object.pk %}">Деактивировать клиента</a>
                {% else %}
                <a class="p-2 btn btn-info" href="{% url 'users:user_change' object.pk %}">Активировать клиента</a>
                {% endif %}
                {% endif %}
            </td>
        </tr>
        {% endfor%}
        </tbody>
    </table>
</div>

{% endblock %}

app/users/templates/users/verify_failed.html
{% extends 'users/base.html' %}

{% block content %}

<p>
    Поражены вашей неудачей :(
</p>
<a href="{% url 'users:login' %}" class="btn btn-link">
    На главную
</a> или
<a href="{% url 'users:register' %}" class="btn btn-link">
    Попробовать еще раз
</a>
ну или
<a href="mailto:support@service.com">Напишите в саппорт</a>

{% endblock %}

app/users/templates/users/verify_success.html
{% extends 'users/base.html' %}

{% block content %}

<p>
    И снова поздравляем! Теперь можно пользоваться сервисом
</p>
<a href="{% url 'users:login' %}" class="btn btn-link">
    На главную
</a>

{% endblock %}

app/users/templates/users/verify_token_expired.html
{% extends 'users/base.html' %}

{% block content %}

<p>
    Токен не дождался :(
</p>
<p>
    Мы удалили пользователя, можете пробовать еще раз
</p>
<a href="{% url 'users:login' %}" class="btn btn-link">
    На главную
</a> или
<a href="{% url 'users:register' %}" class="btn btn-link">
    Попробовать еще раз
</a>
{% endblock %}