app/blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import ArticleListView, ArticleDetailView

app_name = BlogConfig.name

urlpatterns = [
    path('list/', ArticleListView.as_view(), name='list'),
    path('read/<int:pk>/', ArticleDetailView.as_view(), name='read'),
]

app/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
# в алфавитном порядке
urlpatterns = [
    path('', include('users.urls', namespace='users')),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('service/', include('service.urls', namespace='service')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/service/urls.py
from django.urls import path

from service.apps import ServiceConfig
from service.views import *

app_name = ServiceConfig.name

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('customer/', CustomerListView.as_view(), name='service'),
    path('create_customer/', CustomerCreateView.as_view(), name='create_customers'),
    path('mail/', MailingListView.as_view(), name='mail'),
    path('message/', MessageListView.as_view(), name='message'),
    path('create_message/', MessageCreateView.as_view(), name='create_message'),
    path('create_mail/', MailingCreateView.as_view(), name='create_mail'),
    path('update_customer/<int:pk>', CustomerUpdateView.as_view(), name='update_customer'),
    path('update_message/<int:pk>', MessageUpdateView.as_view(), name='update_message'),
    path('update_mail/<int:pk>', MailingUpdateView.as_view(), name='update_mail'),
    path('delete_customer/<int:pk>', CustomerDeleteView.as_view(), name='delete_customer'),
    path('delete_message/<int:pk>', MessageDeleteView.as_view(), name='delete_message'),
    path('delete_mail/<int:pk>', MailingDeleteView.as_view(), name='delete_mail'),
    path('detail_customer/<int:pk>', CustomerDetailView.as_view(), name='detail_customer'),
    path('detail_mail/<int:pk>', MailingDetailView.as_view(), name='detail_mail'),
    path('detail_massage/<int:pk>', MessageDetailView.as_view(), name='detail_message'),
    path('mail_customer/', mail_customer_confirm, name='status'),
    path('statistic/', statistic, name='statistic'),
    path('deactivate_mail/<int:pk>', turn_off_mailing, name='deactivate'),

]

app/users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from users.apps import UsersConfig
from users.views import *


app_name = UsersConfig.name

urlpatterns = [
    path('', SigninView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', SignupView.as_view(), name='register'),
    path('register/success/', SignupSuccessView.as_view(), name='register_success'),
    path('password/reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('password/reset/<uidb64>/confirm/<token>/', CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password/reset/done/',
         CustomPasswordResetDoneView.as_view(template_name='users/reset_confirm.html'), name='password_reset_done'),
    path('password/reset/complete/', CustomPasswordResetCompleteView.as_view(template_name='users/password_reset_form.html'),
         name='password_reset_complete'),
    path('verify/<str:token>/', verify_email, name='verify_email'),
    path('simple/reset/', simple_reset_password, name='simple_reset'),
    path('user_list/', UsersListView.as_view(), name='user_list'),
    path('user_change/<int:pk>/', user_status_change, name='user_change')
]

app/base/models.py
from django.db import models

# Create your models here.

app/service/models.py
from django.db import models
from django.conf import settings
from django.utils.datetime_safe import date

NULLABLE = {'blank': True, 'null': True}


class Customers(models.Model):
    user_create = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='пользователь',
                                    **NULLABLE)
    email = models.CharField(max_length=150, verbose_name='контактный email')
    name = models.CharField(max_length=250, verbose_name='фио')
    comment = models.TextField(verbose_name='комментарий', **NULLABLE)

    def __str__(self):
        return self.name

    class Meta:
        permissions = [
            ('turn_off',
             'Can turn off mailing')
        ]


class Mailing(models.Model):
    objects = None
    PERIOD_ONE_DAY = 'once_day'
    PERIOD_ONE_WEEK = 'once_week'
    PERIOD_ONE_MONTH = 'once_month'
    PERIODS = (
        ('once_day', 'раз в день'),
        ('once_week', 'раз в неделю'),
        ('once_month', 'раз в месяц'),
    )
    STATUSE_COMPLETED = 'completed,'
    STATUSE_CREATED = 'created'
    STATUSE_LAUNCHED = 'launched'
    STATUSE_DEACTIVATION = 'deactivated'
    STATUSES = (
        ('completed', 'завершена'),
        ('created', 'создана'),
        ('launched', 'запущена'),
        ('deactivated', 'деактивирован'),
    )
    user_create = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='пользователь', on_delete=models.CASCADE,
                                    **NULLABLE)
    add_customer = models.ForeignKey('service.Customers', verbose_name='Клиент', on_delete=models.SET_NULL, null=True)
    add_message = models.ForeignKey('service.Message', verbose_name='Сообщение', on_delete=models.SET_NULL, null=True)
    time_mailing = models.TimeField(verbose_name='время рассылки', **NULLABLE)
    change_time = models.CharField(choices=PERIODS, default=PERIOD_ONE_WEEK, max_length=15,
                                   verbose_name='периодичность')
    state_mail = models.CharField(choices=STATUSES, default=STATUSE_COMPLETED, max_length=15,
                                  verbose_name='статус рассылки')
    first_date = models.DateField(default=date.today, verbose_name='начальная_дата', )
    last_date = models.DateField(default=date.today, verbose_name='конечная_дата', )


class Message(models.Model):
    user_create = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='пользователь', on_delete=models.CASCADE,
                                    **NULLABLE)
    topic_message = models.CharField(max_length=250, verbose_name='тема письма', **NULLABLE)
    letter = models.TextField(verbose_name='тело письма')

    def __str__(self):
        return self.topic_message


class TryMail(models.Model):
    date = models.DateTimeField(auto_now_add=True, verbose_name='дата и время последней попытки')
    status = models.CharField(max_length=15, verbose_name='статус попытки')
    answer = models.CharField(max_length=150, verbose_name='ответ почтового сервера', **NULLABLE)

app/base/forms.py
from django import forms


class StyleFormMixin:

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            if isinstance(field.widget, forms.widgets.CheckboxInput):
                field.widget.attrs['class'] = 'form-check-input'
            elif isinstance(field.widget, forms.DateTimeInput):
                field.widget.attrs['class'] = 'form-control flatpickr-basic'
            elif isinstance(field.widget, forms.DateInput):
                field.widget.attrs['class'] = 'form-control datepicker'
            elif isinstance(field.widget, forms.TimeInput):
                field.widget.attrs['class'] = 'form-control flatpickr-time'
            elif isinstance(field.widget, forms.widgets.SelectMultiple):
                field.widget.attrs['class'] = 'form-control select2 select2-multiple'
            elif isinstance(field.widget, forms.widgets.Select):
                field.widget.attrs['class'] = 'form-control select2'
            else:
                field.widget.attrs['class'] = 'form-control'

            field.help_text = ''

app/service/forms.py
from django import forms

from base.forms import StyleFormMixin
from service.models import Customers, Mailing, Message


class CustomerForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Customers
        exclude = ['user_create', ]


class MailingForm(StyleFormMixin, forms.ModelForm):
    STATUSES = (
        ('completed', 'завершена'),
        ('created', 'создана'),
        ('launched', 'запущена'),
    )
    state_mail = forms.ChoiceField(choices=STATUSES, )

    class Meta:
        model = Mailing
        exclude = ['user_create', ]


class MessageForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Message
        exclude = ['user_create', ]

app/base/views.py
from django.shortcuts import render

# Create your views here.

app/service/views/view1.py
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, CreateView

from base.service import count_mail_all, count_active_mail, count_customer_all
from blog.models import Blog
from service.forms import CustomerForm, MailingForm, MessageForm
from service.models import Mailing, Customers, Message


class HomePageView(TemplateView):
    template_name = 'service/home.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['blog'] = Blog.objects.all().order_by('?')[:3]
        context_data['count_all_mail'] = count_mail_all()
        context_data['count_active_mail'] = count_active_mail()
        context_data['customer'] = count_customer_all()
        return context_data


class MailingListView(ListView):
    model = Mailing

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.request.user.has_perm('service.view_mailing'):
            return queryset

        return queryset.filter(user_create=self.request.user)


class CustomerCreateView(CreateView):
    model = Customers
    form_class = CustomerForm
    success_url = reverse_lazy('service:service')

    def form_valid(self, form):
        if form.is_valid():
            self.object = form.save(commit=False)
            self.object.user_create = self.request.user
            self.object.save()
        return super().form_valid(form)


class MailingCreateView(CreateView):
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('service:mail')

    def form_valid(self, form):
        if form.is_valid():
            self.object = form.save(commit=False)
            self.object.user_create = self.request.user
            self.object.save()
        return super().form_valid(form)


class MessageCreateView(CreateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('service:message')

    def form_valid(self, form):
        if form.is_valid():
            self.object = form.save(commit=False)
            self.object.user_create = self.request.user
            self.object.save()
        return super().form_valid(form)

app/service/views/view2.py
from django.contrib.auth.decorators import permission_required
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse

from service.models import TryMail, Mailing
from service.sendmail import mail_customer


def statistic(request):
    context = {
        'object_list': TryMail.objects.all()
    }
    return render(request, 'service/statistic.html', context)


def mail_customer_confirm(request):
    id = request.user.id
    mail_customer(id)
    return redirect(reverse('service:mail'))


@permission_required('service.turn_off')
def turn_off_mailing(request, pk):
    current_mailing = get_object_or_404(Mailing, pk=pk)
    if current_mailing:
        current_mailing.state_mail = Mailing.STATUSE_DEACTIVATION
        current_mailing.save()
    return redirect(request.META.get('HTTP_REFERER'))

app/service/views/view3.py
from msilib.schema import ListView

from django.urls import reverse_lazy
from django.views.generic import UpdateView, DeleteView, DetailView

from service.forms import CustomerForm, MessageForm, MailingForm
from service.models import Customers, Message, Mailing


class UserFilterMixin:
    def get_queryset(self):
        return self.model.objects.filter(user_create=self.request.user)


class CustomerListView(ListView, UserFilterMixin):
    model = Customers


class MessageListView(ListView, UserFilterMixin):
    model = Message


class CustomerUpdateView(UpdateView, UserFilterMixin):
    model = Customers
    form_class = CustomerForm
    success_url = reverse_lazy('service:service')


class MessageUpdateView(UpdateView, UserFilterMixin):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('service:message')


class MailingUpdateView(UpdateView, UserFilterMixin):
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('service:mail')


class CustomerDeleteView(DeleteView, UserFilterMixin):
    model = Customers
    success_url = reverse_lazy('service:service')


class MessageDeleteView(DeleteView, UserFilterMixin):
    model = Message
    success_url = reverse_lazy('service:message')


class MailingDeleteView(DeleteView, UserFilterMixin):
    model = Mailing
    success_url = reverse_lazy('service:mail')


class CustomerDetailView(DetailView, UserFilterMixin):
    model = Customers


class MailingDetailView(DetailView, UserFilterMixin):
    model = Mailing


class MessageDetailView(DetailView, UserFilterMixin):
    model = Message

app/service/templates/service/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title> Cервис управления рассылками</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body {
            background: linear-gradient(white, pink);
            background: linear-gradient(to bottom right, white, grey);
            background-attachment: fixed;
        }
    </style>


</head>
<body>

<div class="float-end">

    {% if user.is_authenticated %}
    {% if perms.users.change_status %}
    <a class="me-3 py-2 text-dark text-decoration-none btn btn-outline-warning"
       href="{% url 'users:user_list' %}">Пользователи</a>
    {% endif %}
    <a class="me-3 py-2 text-dark text-decoration-none btn btn-outline-warning"
       href="{% url 'service:home' %}">Главная</a>
    <a class="me-3 py-2 text-dark text-decoration-none btn btn-outline-warning"
       href="{% url 'blog:list' %}">Блог</a>
    <a class="me-3 py-2 text-dark text-decoration-none btn btn-outline-warning"
       href="{% url 'users:logout' %}">Выход</a>
    {% else %}
    <a class="me-3 py-2 text-dark text-decoration-none btn btn-outline-primary"
       href="{% url 'users:login' %}">Вход</a>
    {% endif %}
</div>
{% include 'service/includes/main-menu.html' %}
{% block content %}
{% endblock %}


<div class="'container">
    <table class="table-primary">
        {% for object in list_object %}
        <tr>
            <td>object.name</td>
            <td>object.title</td>
        </tr>
        {% endfor%}
    </table>
</div>
</div>
{% include 'service/includes/footer.html' %}
<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>

app/service/templates/service/customers_detail.html
{% extends 'service/base.html' %}
{% block content %}
<div class="container">
    <div class="card text-center" style="width: 30rem;">
        <div class="card-body">
        </div>
        <div class="photo">
            <img src="/static/customer.jpg" alt="" border=5 height=300 width=400>
        </div>
        <div class="description">
            <h2>{{object.name}}</h2>
            <h4> {{object.email}}</h4>
            <h1>{{object.comment}} </h1>
            <p>{{object.mailing.state_mail}}</p>
            <button><a class="btn btn-warning" href="{% url 'service:update_customer' object.pk %}">Изменить</a>
            </button>
            <button><a class="btn btn-warning" href="{% url 'service:delete_customer' object.pk %}">Удалить</a></button>

        </div>
    </div>
</div>

{% endblock %}

app/service/templates/service/customers_form.html
{% extends 'service/base.html' %}
{% block content %}
<div class="row">
    <div class="col-4">
        <div class="card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button class="submit"> Добавить</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/service/templates/service/customers_list.html
{% extends 'service/base.html' %}
{% block content %}
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-primery border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Service</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-warning" href="{% url 'service:create_customers' %}">Добавить клиента</a>
    </nav>
</div>
<div class="container">
    <table class="table">
        <thead class="table-light" style="text-align: center">
        <th scope="col">контактный email</th>
        <th scope="col">фио</th>
        <th scope="col">комментарий</th>
        <th scope="col"></th>
        </thead>
        <tbody>
        {% for object in object_list %}
        <tr>
            <td class="table-light" style="text-align: center">{{object.email}}</td>
            <td class="table-light" style="text-align: center">{{object.name}}</td>
            <td class="table-light" style="text-align: center">{{object.comment}}</td>
            <td class="table-light" style="text-align: center">
                <a class="btn btn-warning" href="{% url 'service:detail_customer' object.pk %}">Просмотр</a>
            </td>

        </tr>
        {% endfor%}

        </tbody>
    </table>
</div>

{% endblock %}

app/service/templates/service/home.html
{% extends 'service/base.html' %}

{% block content %}
<div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
    <div class="col-12">
        <div class="card mb-4 rounded-3 shadow-sm">
            <div class="card-header py-3">
                <h4 class="my-0 fw-normal">Наша статистика</h4>
            </div>
            <div class="card-body">
                <ul class="list-unstyled mt-3 mb-4">
                    <li>Всего рассылок : {{count_all_mail}}</li>
                    <li>Активных рассылок всего : {{count_active_mail}}</li>
                    <li>Количество уникальных клиентов для рассылок : {{customer}}</li>
                </ul>
                <a class="w-100 me-3 py-2 text-dark text-decoration-none btn btn-outline-warning"
                   href="{% url 'service:service' %}">Перейти в приложение</a>
            </div>
        </div>
    </div>
</div>

<h2 class="display-6 text-center mb-4">Последние статьи</h2>
<div class="row">
    {% for item in blog %}
    <div class="col-md-6">
        <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
            <div class="col p-4 d-flex flex-column position-static">
                <strong class="d-inline-block mb-2 text-dark-emphasis">{{ item.title }}</strong>
                <h3 class="mb-0">{{ item.title }}</h3>
                <div class="mb-1 text-muted">{{ item.date|date:"d M" }}</div>
                <p class="card-text mb-auto">{{ item.text|slice:150 }}...</p>
                <a href="{% url 'blog:read' item.pk %}" class="stretched-link text-dark-emphasis">Continue reading</a>
            </div>
            <div class="col-auto d-none d-lg-block">
                <svg class="bd-placeholder-img" width="200" height="250" xmlns="http://www.w3.org/2000/svg"
                     role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice"
                     focusable="false"><title>Placeholder</title>
                    <img src="/media/{{ item.image }}" alt="" border=3 height=250 width=450></img>
                    <text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text>
                </svg>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

app/service/templates/service/mailing_confirm_delete.html
{% extends 'service/base.html' %}
{% block content %}
<div class="row">
    <div class="col-4">
        <div class="card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <p>
                        Вы действительно хотите удалить рассылку в {{object.time_mailing}} ?
                    </p>
                    <a class="btn btn-info" href="{% url 'service:mail' %}">Отменить</a>
                    <button class="submit">Подтвердить</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/service/templates/service/mailing_detail.html
{% extends 'service/base.html' %}
{% block content %}
<div class="container">
    <div class="card text-center" style="width: 30rem;">
        <div class="card-body">
        </div>
        <div class="photo">
            <img src="/static/mailing.png" alt="" border=5 height=200 width=300>
        </div>
        <div class="description">
            <h2> Отправить на почту : {{object.add_customer.email}}</h2>
            <h4> Начиная с даты : {{object.first_date}}</h4>
            <h4> Начиная со времени : {{object.time_mailing}}</h4>
            <h4> Заканчивая до : {{object.last_date}}</h4>
            <h1> Периодичность : {{object.change_time}} </h1>
            <h1> Статус отправки : {{object.state_mail}} </h1>
            <p> Тема письма : {{object.add_message.topic_message}}</p>
            <p> Текст письма : {{object.add_message.letter}}</p>
            <td>
                <button><a class="btn btn-info" href="{% url 'service:update_mail' object.pk %}">Изменить</a></button>
                <button><a class="btn btn-info" href="{% url 'service:delete_mail' object.pk %}">Удалить</a></button>
        </div>
    </div>
</div>

{% endblock %}

app/service/templates/service/mailing_form.html
{% extends 'service/base.html' %}
{% block content %}
<div class="row">
    <div class="col-4">
        <div class="card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button class="submit"> Добавить</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/service/templates/service/mailing_list.html
{% extends 'service/base.html' %}
{% block content %}
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-primery border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Service</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-warning" href="{% url 'service:create_mail' %}">Добавить рассылку</a>
        <a class="btn btn-outline-dark" href="{% url 'service:status' %}">Отправить всем сообщения сейчас</a>
    </nav>
</div>
<div class="container">
    <table class="table">
        <thead class="table-light" style="text-align: center">
        <th scope="col">кому</th>
        <th scope="col">начать</th>
        <th scope="col">закончить</th>
        <th scope="col">время рассылки</th>
        <th scope="col">периодичность:</th>
        <th scope="col">статус рассылки</th>
        <th scope="col">тема письма</th>
        <th scope="col"></th>
        <th scope="col"></th>
        <th scope="col"></th>
        </thead>
        <tbody>
        {% for object in object_list %}
        <tr>
            <td class="table-light" style="text-align: center">{{object.add_customer.email}}</td>
            <td class="table-light" style="text-align: center">{{object.first_date}}</td>
            <td class="table-light" style="text-align: center">{{object.last_date}}</td>
            <td class="table-light" style="text-align: center">{{object.time_mailing}}</td>
            <td class="table-light" style="text-align: center">{{object.change_time}}</td>
            <td class="table-light" style="text-align: center">{{object.state_mail}}</td>
            <td class="table-light" style="text-align: center">{{object.add_message.topic_message}}</td>
            <td class="table-light" style="text-align: center">
                <a class="btn btn-warning" href="{% url 'service:detail_mail' object.pk %}">Просмотр</a>
            </td>
            {% if perms.service.turn_off %}
            <td class="table-light" style="text-align: center">
                <a class="btn btn-info" href="{% url 'service:deactivate' object.pk %}">Deactivate</a>
            </td>
            {% endif %}
        </tr>
        {% endfor%}

        </tbody>
    </table>
</div>

{% endblock %}

app/service/templates/service/message_confirm_delete.html
{% extends 'service/base.html' %}
{% block content %}
<div class="row">
    <div class="col-4">
        <div class="card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <p>
                        Вы действительно хотите удалить сообщение {{object.topic_message}} ?
                    </p>
                    <a class="btn btn-info" href="{% url 'service:message' %}">Отменить</a>
                    <button class="submit">Подтвердить</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/service/templates/service/message_detail.html
{% extends 'service/base.html' %}
{% block content %}
<div class="container">
    <div class="card text-center" style="width: 30rem;">
        <div class="card-body">
        </div>
        <div class="photo">
            <img src="/static/message.jpg" alt="" border=5 height=300 width=400>
        </div>
        <div class="description">
            <h2>{{object.topic_message}}</h2>
            <p>{{object.letter}}</p>
            <button><a class="btn btn-warning" href="{% url 'service:update_message' object.pk %}">Изменить</a></button>
            <button><a class="btn btn-warning" href="{% url 'service:delete_message' object.pk %}">Удалить</a></button>
        </div>
    </div>
</div>

{% endblock %}

app/service/templates/service/message_form.html
{% extends 'service/base.html' %}
{% block content %}
<div class="row">
    <div class="col-4">
        <div class="card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button class="submit"> Добавить</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/service/templates/service/message_list.html
{% extends 'service/base.html' %}
{% block content %}
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-primery border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Service</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-warning" href="{% url 'service:create_message' %}">Добавить письмо</a>
    </nav>
</div>
<div class="container">
    <table class="table">
        <thead class="table-light" style="text-align: center">

        <th scope="col">тема письма</th>
        <th scope="col">тело письма</th>
        <th scope="col"></th>
        <th scope="col"></th>
        <th scope="col"></th>
        </thead>
        <tbody>
        {% for object in object_list %}
        <tr>
            <td class="table-light" style="text-align: center">{{object.topic_message}}</td>
            <td class="table-light" style="text-align: center">{{object.letter}}</td>
            <td class="table-light" style="text-align: center">
                <a class="btn btn-warning" href="{% url 'service:detail_message' object.pk %}">Просмотр</a>
            </td>
        </tr>
        {% endfor%}

        </tbody>
    </table>
</div>

{% endblock %}

app/service/templates/service/statistic.html
{% extends 'service/base.html' %}
{% block content %}
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-primery border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Service</h5>
</div>
<div class="container">
    <table class="table">
        <thead class="table-light" style="text-align: center">
        <th scope="col"></th>
        <th scope="col">Дата и время попытки</th>
        <th scope="col">Cтатус попытки</th>
        <th scope="col">Ответ почтового сервера</th>


        </thead>
        <tbody>
        {% for object in object_list %}
        <tr>
            <td class="table-light" style="text-align: center">{{object.id}}</td>
            <td class="table-light" style="text-align: center">{{object.date}}</td>
            <td class="table-light" style="text-align: center">{{object.status}}</td>
            <td class="table-light" style="text-align: center">{{object.answer}}</td>

        </tr>
        {% endfor%}

        </tbody>
    </table>
</div>
{% endblock%}